{"name": "test_b", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0", "trace": "@pytest.mark.run(order=2)\n    def test_b():\n        print(\"\\ntest_b\")\n>       assert 0\nE       assert 0\n\nscripts\\test_order.py:17: AssertionError"}, "start": 1584329536997, "stop": 1584329536997, "uuid": "a792f512-b9fb-4e14-8590-5062961e6d87", "historyId": "6de8a25256d80f86d8db393e29f44d16", "testCaseId": "babacb60233942e9ed5469c0887731b4", "fullName": "scripts.test_order#test_b", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_order"}, {"name": "host", "value": "X84DLS8ARYVJRTM"}, {"name": "thread", "value": "20872-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_order"}]}